# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/.devcontainer/Dockerfile'
        tags: |
          $(tag)
  - job: Phase_1
    steps:
    - checkout: self
    - task: SonarQubePrepare@4
      displayName: Prepare analysis on SonarQube
      inputs:
        SonarQube: teste2
        projectKey: ckp-teste-cloudhub
        projectName: ckp teste cloudhub
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        projects: '**/*.java'
    - task: SonarQubeAnalyze@4
      displayName: Run Code Analysis
    - task: SonarQubePublish@4
      displayName: Publish Quality Gate Result
